apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  namespace: smart-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-app
  template:
    metadata:
      labels:
        app: proxy-app
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: smart-agent-reader
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app   # 用于节点的标签键
                operator: In
                values:
                - proxy-app    # 与标签键匹配的值
      volumes:
      - name: node-volume
        hostPath:
          path: /home/cn/node/
          type: DirectoryOrCreate
      containers:
        - name: my-agent
          image: docker.io/library/my-agent
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: node-volume
            mountPath: /app/node/
          ports:
            - containerPort: 8081
              protocol: TCP
            - containerPort: 8082
              protocol: TCP
            - containerPort: 8083
              protocol: UDP
          resources: # 这里添加资源请求和限制
            requests:
              cpu: "500m" # 请求至少0.5核的CPU
            limits:
              cpu: "2000m" # 限制最多1核的CPU
   

---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: smart-agent
spec:
  selector:
    app: proxy-app
  type: NodePort
  ports:
    - name: "client-port"
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: "ping-port"
      protocol: UDP
      port: 8083
      targetPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: cluster-service
  namespace: smart-agent
spec:
  selector:
    app: proxy-app
  type: ClusterIP
  ports:
    - name: "cluster-port"
      protocol: TCP
      port: 8082
      targetPort: 8082
    
