apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-agent-deployment
  namespace: smart-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-agent
  template:
    metadata:
      labels:
        app: my-agent
    spec:
      containers:
        - name: my-agent
          image: my-agent
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
              protocol: TCP
            - containerPort: 8082
              protocol: TCP
            - containerPort: 8083
              protocol: UDP

---
apiVersion: v1
kind: Service
metadata:
  name: my-agent-service
  namespace: smart-agent
spec:
  selector:
    app: my-agent
  type: NodePort
  ports:
    - name: "client-port"
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: "ping-port"
      protocol: UDP
      port: 8083
      targetPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: cluster-service
  namespace: smart-agent
spec:
  selector:
    app: my-agent
  type: ClusterIP
  ports:
    - name: "cluster-port"
      protocol: TCP
      port: 8082
      targetPort: 8082
